name: fading_edge_scrollview
description: Package providing FadingEdgeScrollView which allows you to build scrollable views with fading edges
version: 4.0.0
homepage: https://github.com/mponkin/fading_edge_scrollview

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
